name: carla-fault-injection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pyyaml
  - pillow
  - imageio
  - imageio-ffmpeg
  - shapely
  - networkx
  - pip
  - pip:
      - carla==0.9.15